### ISSUE TITLE
Stolen from Rammerhead (fork removed)

### ISSUE THREAD

**Issue by eris-webserv** [s191ed/rammerheader#1]
This repo is a clone of https://github.com/binary-person/rammerhead without the fork notice.

**Comment by s191ed** [comment]
why would i need a fork notice?

**Comment by eris-webserv** [comment]
Because it's standard for when you clone someone's repositories? You literally went through the effort to copy the repository in such a way to avoid it >:/

**Comment by s191ed** [comment]
i didnt mean to unfork it?? the name is not changed and binary is still the author in the master file. i probably changed some stuff because i had to make it work on replit

**Comment by eris-webserv** [comment]
Hmm, I may be wrong. Just a bit paranoid is all. 

I see why though- Replit has a ToS ban on proxies. You were most likely stopped by them because of that.
